# Generated by Django 5.1.2 on 2024-10-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0003_rename_name_jsondata_name_remove_jsondata_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='CustomerID',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
