# Generated by Django 5.1.2 on 2024-10-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0004_alter_jsondata_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id_numeric', models.IntegerField(default=0)),
                ('age_normalized', models.FloatField(null=True)),
                ('gender_encoded', models.IntegerField(default=0)),
                ('region_encoded', models.IntegerField(default=0)),
                ('city_encoded', models.IntegerField(default=0)),
                ('interests_encoded', models.JSONField(default=list)),
                ('purchase_history_encoded', models.JSONField(default=list)),
                ('days_since_purchase', models.IntegerField(null=True)),
                ('feedback_encoded', models.IntegerField(default=0)),
                ('income_level_encoded', models.IntegerField(default=0)),
                ('encoding_mapping', models.JSONField(default=dict)),
                ('original_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_representation', to='dataupload.jsondata')),
            ],
        ),
    ]
