# Generated by Django 5.1.2 on 2024-10-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0005_numericcustomerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumericCustomerData',
        ),
    ]
