# Generated by Django 5.1.2 on 2024-10-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0006_delete_numericcustomerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_normalized', models.FloatField(null=True)),
                ('gender_encoded', models.IntegerField(null=True)),
                ('region_encoded', models.IntegerField(null=True)),
                ('city_encoded', models.IntegerField(null=True)),
                ('interests_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('purchase_total', models.FloatField(default=0.0)),
                ('days_since_last_purchase', models.IntegerField(null=True)),
                ('feedback_sentiment', models.FloatField(null=True)),
                ('income_level_encoded', models.IntegerField(null=True)),
                ('original_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataupload.jsondata')),
            ],
            options={
                'indexes': [models.Index(fields=['original_data'], name='dataupload__origina_8cf112_idx')],
            },
        ),
    ]
