# Generated by Django 5.1.2 on 2024-10-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0008_delete_numericcustomerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(default='unknown', max_length=50, unique=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.IntegerField(blank=True, null=True)),
                ('Region', models.IntegerField(blank=True, null=True)),
                ('City', models.IntegerField(blank=True, null=True)),
                ('Interests', models.JSONField(blank=True, default=dict)),
                ('Feedback', models.IntegerField(blank=True, null=True)),
                ('Income_Level', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
