# Generated by Django 5.1.2 on 2024-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0009_numericdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericdata',
            name='Purchase_History',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
