# Generated by Django 5.1.2 on 2024-10-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0010_numericdata_purchase_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('feature1', models.CharField(max_length=50)),
                ('feature2', models.CharField(max_length=50)),
                ('plot_path', models.CharField(max_length=255)),
                ('total_samples', models.IntegerField()),
                ('number_of_clusters', models.IntegerField(default=3)),
                ('silhouette_score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField()),
                ('sample_count', models.IntegerField()),
                ('feature1_mean', models.FloatField()),
                ('feature1_std', models.FloatField()),
                ('feature2_mean', models.FloatField()),
                ('feature2_std', models.FloatField()),
                ('centroid_feature1', models.FloatField()),
                ('centroid_feature2', models.FloatField()),
                ('cluster_density', models.FloatField(null=True)),
                ('customer_ids', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='dataupload.clusteranalysis')),
            ],
            options={
                'unique_together': {('analysis', 'cluster_number')},
            },
        ),
    ]
