# Generated by Django 5.1.2 on 2024-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0011_clusteranalysis_clusterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='plots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
